#### Arrays can be created using Python's built-in list data structure or using libraries like numpy for more advanced array operations

##### Creating Arrays : Create One Dimentional Array and Two Dimentional Array

In [2]:
# One-dimensional list
arr = [1, 2, 3, 4, 5]
print("1-D Array: ",arr)

# Two-dimensional array using numpy
import numpy as np
arr_2d = np.array([[1, 2], [3, 4]])
print("2-D Array: ")
print(arr_2d)

# Three-dimensiona array using numpy
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3-D Array: ")
print(arr_3d)

1-D Array:  [1, 2, 3, 4, 5]
2-D Array: 
[[1 2]
 [3 4]]
3-D Array: 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##### Accessing Elements : Access elements using indices. Python uses 0-based indexing, meaning the first element is at index 0.

In [3]:
# Accessing elements
first_element = arr[0]  # Output: 1
element_2d = arr_2d[1, 0]  # Output: 3
element_3d = arr_3d[0,0,1]
print("Accessing 1D Element:",first_element)
print("Accessing 2D Element:",element_2d)
print("Accessing 3D Element:", element_3d)

Accessing 1D Element: 1
Accessing 2D Element: 3
Accessing 3D Element: 2


##### Array Slicing : Slicing is used to access a range of elements from an array. The syntax is array[start:stop:step].

In [4]:
# Slicing
first_three = arr[:3]  # Output: [1, 2, 3]
print("First 3 Elements: ",first_three)

First 3 Elements:  [1, 2, 3]


##### Array Length : The len() function is used to determine the number of elements in an array.

In [5]:
length = len(arr)
print("Length of Array: ",length)

Length of Array:  5


#### Modifying Array: Arrays can be modified by assigning new values to specific indices or by appending new elements.

In [6]:
# Modifying array elements
arr[1] = 10  # arr becomes [1, 10, 3, 4, 5]
print("Old Array: ",arr)
arr.append(6)  # arr becomes [1, 10, 3, 4, 5, 6]
print("New Array: ",arr)

Old Array:  [1, 10, 3, 4, 5]
New Array:  [1, 10, 3, 4, 5, 6]


##### Iterating Arrays : Use loops to iterate over elements in an array

In [7]:
# Iterating over an array
for element in arr:
    print(element)

1
10
3
4
5
6


##### Array Operations with numpy : numpy allows for efficient array operations like addition, subtraction, and element-wise multiplication

In [9]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2  # Output: [5, 7, 9]
result

array([5, 7, 9])

##### Reshaping Arrays : The shape of an array can be changed using the reshape() method in numpy.

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Output: [[1, 2, 3], [4, 5, 6]]
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

##### Array Broadcasting : Broadcasting in numpy allows arrays of different shapes to be used in arithmetic operations.

In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4], [5], [6]])
result = arr1 + arr2  # Broadcasting adds arr1 to each row of arr2
result

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

##### Array Aggregation : Aggregation operations like sum, min, and max can be performed on arrays.

In [16]:
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)  # Output: 15
print("Sum: ",total)
minimum = np.min(arr)
print("Minimum: ",minimum)
maximum = np.max(arr)
print("Maximum: ",maximum)

Sum:  15
Minimum:  1
Maximum:  5
